apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-jar-deployment
  namespace: dev
  labels:
    app: springboot-jar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-jar
  template:
    metadata:
      namespace: dev
      labels:
        app: springboot-jar
    spec:
      containers:
      - name: springboot-jar
        image: jithendradevops/springboot-jar:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockerhub-creds
